const employeeQueue = [
    {
      id: 1,
      fullName: 'Иванов Иван Иванович',
      department: 'IT',
      position: 'Системный администратор',
      status: 'В ожидании',
      createdAt: '2025-06-04 12:23',
    },
    {
      id: 2,
      fullName: 'Петрова Мария Сергеевна',
      department: 'HR',
      position: 'HR-менеджер',
      status: 'Создано',
      createdAt: '2025-06-04 13:45',
    },
    {
      id: 3,
      fullName: 'Сидоров Алексей Петрович',
      department: 'Финансы',
      position: 'Бухгалтер',
      status: 'Ошибка',
      createdAt: '2025-06-04 14:15',
    },
    {
      id: 4,
      fullName: 'Кузнецова Елена Андреевна',
      department: 'Маркетинг',
      position: 'Маркетолог',
      status: 'В ожидании',
      createdAt: '2025-06-04 15:10',
    },
    {
      id: 5,
      fullName: 'Морозов Павел Евгеньевич',
      department: 'IT',
      position: 'Разработчик',
      status: 'Создано',
      createdAt: '2025-06-04 15:30',
    },
    {
      id: 6,
      fullName: 'Фёдорова Ольга Викторовна',
      department: 'Продажи',
      position: 'Менеджер по продажам',
      status: 'Ошибка',
      createdAt: '2025-06-04 16:00',
    },
    {
      id: 7,
      fullName: 'Денисов Артём Сергеевич',
      department: 'Юридический',
      position: 'Юрист',
      status: 'Создано',
      createdAt: '2025-06-04 16:25',
    },
    {
      id: 8,
      fullName: 'Беляева Анастасия Дмитриевна',
      department: 'Кадры',
      position: 'Рекрутер',
      status: 'В ожидании',
      createdAt: '2025-06-04 16:45',
    },
    {
      id: 9,
      fullName: 'Григорьев Николай Павлович',
      department: 'IT',
      position: 'DevOps-инженер',
      status: 'Создано',
      createdAt: '2025-06-04 17:05',
    },
    {
      id: 10,
      fullName: 'Александрова Ирина Олеговна',
      department: 'Финансы',
      position: 'Аналитик',
      status: 'Ошибка',
      createdAt: '2025-06-04 17:30',
    },
    {
      id: 11,
      fullName: 'Семенов Виктор Николаевич',
      department: 'Производство',
      position: 'Инженер',
      status: 'Создано',
      createdAt: '2025-06-04 17:55',
    },
    {
      id: 12,
      fullName: 'Мельникова Татьяна Владимировна',
      department: 'Закупки',
      position: 'Специалист по закупкам',
      status: 'В ожидании',
      createdAt: '2025-06-04 18:20',
    },
    {
      id: 13,
      fullName: 'Ковалев Данил Романович',
      department: 'IT',
      position: 'Frontend-разработчик',
      status: 'Создано',
      createdAt: '2025-06-04 18:40',
    },
    {
      id: 14,
      fullName: 'Захарова Анна Игоревна',
      department: 'HR',
      position: 'Специалист по обучению',
      status: 'Ошибка',
      createdAt: '2025-06-04 19:00',
    },
    {
      id: 15,
      fullName: 'Тихонов Сергей Владимирович',
      department: 'IT',
      position: 'Архитектор решений',
      status: 'В ожидании',
      createdAt: '2025-06-04 19:25',
    },
    {
      id: 16,
      fullName: 'Егорова Наталья Петровна',
      department: 'Маркетинг',
      position: 'Копирайтер',
      status: 'Создано',
      createdAt: '2025-06-04 19:45',
    },
    {
      id: 17,
      fullName: 'Борисов Илья Андреевич',
      department: 'Финансы',
      position: 'Экономист',
      status: 'Ошибка',
      createdAt: '2025-06-04 20:10',
    },
    {
      id: 18,
      fullName: 'Волкова Екатерина Александровна',
      department: 'Клиентская поддержка',
      position: 'Оператор',
      status: 'Создано',
      createdAt: '2025-06-04 20:30',
    },
    {
      id: 19,
      fullName: 'Орлов Роман Валентинович',
      department: 'IT',
      position: 'Backend-разработчик',
      status: 'В ожидании',
      createdAt: '2025-06-04 21:00',
    },
    {
      id: 20,
      fullName: 'Лебедева Дарья Константиновна',
      department: 'Финансы',
      position: 'Аудитор',
      status: 'Создано',
      createdAt: '2025-06-04 21:30',
    },
  ];

export default employeeQueue;